### ISSUE TITLE
In new UI style the cleanup action doesn't show changed colours in "led" buttons

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-runner#71] opened 2016-10-11 10:42 UTC
when you press cleanup in the new white UI style the colours of the led images don't change step by step, they change all at once after everything is cleaned up. In earlier versions of Runner the led's changed colour step by step so you could see progress of cleaning up actions.

**Comment by dragoslav** [comment] 2016-10-18 15:04
broken in https://github.com/magneticio/vamp-runner/commit/4f691617b8a7c56dfa50fdbefff08c28340f3d3f instead of displaying cleanup tasks panel actually shows duplicate of recipe run tasks.

**Closed** 2016-10-18 15:05 UTC
